name: ✨ Feature Request
description: Suggest an idea or enhancement for Base Nest
title: "[FEATURE] <short description>"
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        We love new ideas! Please describe your feature request clearly. 🚀

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added or improved?
      placeholder: "I’d like a built-in loading widget for network calls..."

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important or useful?
      placeholder: "This will reduce repetitive UI code across features."

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like it to work?
      placeholder: "Add a shared/loading_widget.dart with standard CircularProgressIndicator..."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other approaches?

  - type: checkboxes
    id: confirmations
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues.
          required: true